MAIN_FILE = $(cliente)cya-P01-Strings.cc
SRC_FILES = $(cadena)cadena.cc $(alfabeto)alfabeto.cc $(simbolo)simbolo.cc
EXECUTABLE_FILE = $(exe)cya-P01-Strings

default: 
	g++ -std=c++14 -g -Wall -o $(EXECUTABLE_FILE) $(MAIN_FILE) $(SRC_FILES)

run:
	./$(EXECUTABLE_FILE)